### PR TITLE
fix some i18n missing strings on UI

### PR DESCRIPTION
**Pull request by listeng**
fix some i18n missing strings on UI

### CODE REVIEW

**Comment by cdujeu** [comment]
hello, thanks for submitting
but this is not really how it works : we only set the en-us strings, then go through CrowdIn to make the translations. 
We'll merge your suggestion manually!
Thx

**Comment by listeng** [comment]
Thanks for your work. The strings in this commit are not available in CrowdIn, because they are hard-coded in UI. As a result, we cannot translate these strings using CrowdIn.

**Comment by cdujeu** [comment]
i will ping you when they are in CrowdIn

**Comment by cdujeu** [comment]
(fixed in code - soon to appear in CrowdIn)

**Pull request closed without merging**
