### PR TITLE
Fix private IP bug

### PR DESCRIPTION
**Pull request by mzch**
Fix a bug that needs nowhere private ip

### CODE REVIEW

**Comment by cdujeu** [comment]
Hi @mzch 
Thanks for contributing! I'm not sure we want to modify the content of the vendor/ folder, as it should kept synced at least with a certain branch of the original repository.
@ghecquet is there anyway to disable this check at the Cells level?

**Comment by cdujeu** [comment]
Hi @mzch we should indeed switch to go modules at one point.
Quick question, would you be interested in participating to translation of Pydio Cells into Japanese?

**Comment by cdujeu** [comment]
We're on Crowd In https://crowdin.com/project/pydio-cells
I think we would have to create a new language, can you sign up (free) and see if you can "propose" a new language?

**Comment by mzch** [comment]
I logged in Crowd and requested to add Japanese language.

**Comment by bsinou** [comment]
Japanese has been added for Pydio Cells in crowdin. Thanks for helping and don't hesitate if you have any question.

**Comment by bsinou** [comment]
Hey @mzch, just for the record, I had to remove and re-add the Japanese language in the crowdin project to insure generated file names respect our internal conventions. But now everything is up and running. So feel free to jump in at any time.

**Comment by cdujeu** [comment]
Finally fixed in 1.4.1 => pass an address via services options instead of hacking the lib.

**Pull request closed without merging**
