### PR TITLE
Add custom ssl certificate to environment.

### PR DESCRIPTION
**Pull request by tinymins**
This feature will help quick start docker with a valid custom certificate, eg: an auto generated let's encrypt X3 cert.

### CODE REVIEW

**Comment by tinymins** [comment]
For #18.

**Comment by cdujeu** [comment]
Hi @tinymins sorry for the looong delay :-) We are reviewing your PR and we would like to merge it, but can you kindly sign the CLA before? See https://pydio.com/en/community/contribute/contributor-license-agreement-cla
Thanks!

**Comment by tinymins** [comment]
@cdujeu Seems everything ok?
image

**Comment by cdujeu** [comment]
yep thanks !

**Comment by tinymins** [comment]
Hi everyone, shouldn't we do a `git rebase` on this branch instead of merging a lot of commits to this branch?

**Comment by tinymins** [comment]
https://github.com/tinymins/pydio-cells/tree/add-custom-ssl-rebased Just like this branch?

**Comment by bsinou** [comment]
About the  content:
- I have merged and cleaned your proposal for the new flags in the non interactive install
- I reverted your changes in the docker-compose.yml file: we want to keep self signed certificate as the default for the time being. Yet, I have added a ReadMe with samples for the various configurations including yours 
- I have rewritten and cleaned the docker entry point to support the 4 type of deployment we have: provided cert, let's encrypt, self-signed and no certificate.

I still have to double check and test the new docker entry point but then we should be good to merge back into master.

**Comment by tinymins** [comment]
Hi @bsinou, I'v read those changes, and also rewrite the logic for 4 types. Just like the branch link I'v mentioned above. Seems the only thing I need to do is to revert default config.

**Comment by bsinou** [comment]
About the "git process", I have basically done a rebased of **your pull request** on the latest origin master yesterday. Yet I must admit it looks _not so clean_ here.
I might report all changes in one commit in your other branch before the merge once I have tested everything to keep a clean history.

**Comment by bsinou** [comment]
> Hi @bsinou, I'v read those changes, and also rewrite the logic for 4 types. Just like the branch link I'v mentioned above. Seems the only thing I need to do is to revert default config.

Could you please precise what you mean ? I did not get your point / understood what you want to say. (Maybe because I am not awake enough ... It's still early here)

**Comment by tinymins** [comment]
> > Hi @bsinou, I'v read those changes, and also rewrite the logic for 4 types. Just like the branch link I'v mentioned above. Seems the only thing I need to do is to revert default config.
> 
> Could you please precise what you mean ? I did not get your point / understood what you want to say. (Maybe because I am not awake enough ... It's still early here)

Sorry for that, I'm at airport now and typing from my cell phone.

What I want to say is that I also did a rebase job yesterday, and here it is: https://github.com/tinymins/pydio-cells/tree/add-custom-ssl-rebased
I can revert the change of docker-compose.yml file from this PR according to your opinion.

I just got confused why there is a lot of commits merged from master branch yesterday.

Thanks

**Comment by tinymins** [comment]
> About the "git process", I have basically done a rebased of **your pull request** on the latest origin master yesterday. Yet I must admit it looks _not so clean_ here.
> I might report all changes in one commit in your other branch before the merge once I have tested everything to keep a clean history.

And now, seems I understand why. I'll waiting for your test. 😄

**Comment by bsinou** [comment]
Hello.

I have tested and fixed a small typo. We should be good to go. 

Could you please have a look and test to see if your issue is addressed ? 

For the record, if necessary, you can pull a pre-built development image on docker hub with bsinou/cells:unstable tag.

**Pull request merged**
