### PR TITLE
Python script for side-way file/keys decryption

### PR DESCRIPTION
**Pull request by drzraf**
Side-way decryption of keys & encrypted file.
https://forum.pydio.com/t/doc-password-encrypted-encryption-key-how-to-decrypt-it-using-the-password/3123/1

### CODE REVIEW

**Comment by drzraf** [comment]
Didn't you feel it fit the docs/tools? Or would it be that Python isn't welcomed in this Go-repository ? :)

**Comment by cdujeu** [comment]
Being named **Py**dio and discriminate python would be a shame :-)
we'll recheck if it's the right place for that

**Comment by bsinou** [comment]
Hey @drzraf,

We could integrate your script for the next release. Yet, we want to locate it in the "tools/scripts" directory that I've just created.
Could you please rebase and adapt your PR ? 

Also, and before we merge the PR, you must sign our CLA. 

You can find it here: 
https://pydio.com/en/community/contribute/contributor-license-agreement-cla

It has a quite standard copyright clause => you should also adapt the header of your file with the AGPLv3 License and a shared copyright for you and Abstrium SAS.

Once again, thanks for the help!

**Comment by bsinou** [comment]
I've merged your PR.
(we then finally moved it to a "contribs" sub folder that seems more relevant for the time being).
 Thanks again!

**Pull request merged**
